# Generated by Django 4.2.7 on 2024-01-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, verbose_name='Текстовое содержимое')),
                ('city_salary_graph', models.ImageField(upload_to='binary_data/%Y/%m/%d', verbose_name='График уровня зарплат по городам')),
                ('city_vacancy_graph', models.ImageField(upload_to='binary_data/%Y/%m/%d', verbose_name='График доли вакансий по городам')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LatestApiVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Название вакансии')),
                ('vacancy_info', models.TextField(max_length=15, verbose_name='Информация о вакансии')),
            ],
        ),
        migrations.CreateModel(
            name='MainBinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_binary', models.ImageField(upload_to='binary_data/%Y/%m/%d', verbose_name='Бинарный файл')),
                ('text_content', models.TextField(blank=True, verbose_name='Текстовое содержимое')),
                ('job_description', models.TextField(blank=True, verbose_name='Описание профессии')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavBinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_binary', models.ImageField(upload_to='binary_data/%Y/%m/%d', verbose_name='Бинарный файл')),
                ('heading', models.CharField(max_length=100, verbose_name='Заголовок вакансии')),
                ('menu_item_1', models.CharField(max_length=25, verbose_name='Первый пункт меню')),
                ('menu_item_2', models.CharField(max_length=25, verbose_name='Второй пункт меню')),
                ('menu_item_3', models.CharField(max_length=25, verbose_name='Третий пункт меню')),
                ('menu_item_4', models.CharField(max_length=25, verbose_name='Четвертый пункт меню')),
                ('menu_item_5', models.CharField(max_length=25, verbose_name='Пятый пункт меню')),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelevanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, verbose_name='Текстовое содержимое')),
                ('salary_graph', models.ImageField(upload_to='binary_data/%Y/%m/%d', verbose_name='График уровня зарплат по годам')),
                ('vacancy_graph', models.ImageField(upload_to='binary_data/%Y/%m/%d', verbose_name='График количества вакансий по годам')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, verbose_name='Текстовое содержимое')),
                ('table_identifier', models.CharField(max_length=30, verbose_name='Идентификатор таблицы')),
                ('skills_graphic', models.ImageField(upload_to='binary_data/%Y/%m/%d', verbose_name='График по навыкам')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LastVacancyModel',
        ),
    ]
