# Generated by Django 4.2.7 on 2024-01-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_director', '0003_remove_mainbinary_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestapivacancy',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='latestapivacancy',
            name='vacancy_info',
        ),
        migrations.AddField(
            model_name='latestapivacancy',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestapivacancy',
            name='vacancy',
            field=models.TextField(default=1, max_length=15, verbose_name='Вакансия для парсинга'),
            preserve_default=False,
        ),
    ]
